name: Tests

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

permissions:
  contents: read

env:
  NODE_VERSION: latest
  PHP_VERSION: 8.3

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.operating-system }}
    name: OS ${{ matrix.operating-system }}

    steps:
      - name: Setup PHP ${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, intl, xdebug, json, sockets, gd
          ini-values: max_execution_time=360
          coverage: xdebug
          tools: php-cs-fixer, phpunit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PHP info
        run: php -v

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install Node.js dependencies
        run: npm ci
      - name: Starting local web server
        # bash shell is required for Windows, otherwise the background
        # server does not start and work properly
        shell: bash
        run: npm run start-server &
      - name: Wait for server to start up
        run: npx wait-on --timeout 15000 http://127.0.0.1:3000
      - name: Server warm up
        run: sleep 5

      - name: Run test suite
        shell: bash
        run: npm run test
